const { HfInference } = require("@huggingface/inference");
const Order = require("../models/order");
const Product = require("../models/product");
const config = require("../config/index");

// Fallback recommendations: get products from the same category as user's last purchased item
const getFallbackRecommendations = async (userId) => {
  const lastOrder = await Order.findOne({ user: userId })
    .populate("product")
    .sort({ createdAt: -1 });

  let filter = { stock: { $gt: 0 } };
  if (lastOrder && lastOrder.product) {
    filter.category = lastOrder.product.category;
    filter._id = { $ne: lastOrder.product._id };
  }

  const recommendations = await Product.find(filter)
    .sort({ rating: -1 })
    .limit(4)
    .lean();

  return recommendations;
};

const getRecommendations = async (userId) => {
  try {
    const fallback = await getFallbackRecommendations(userId);

    if (!config.HUGGINGFACE_API_KEY) {
      return {
        recommendedProducts: fallback,
        source: "fallback",
        reason: "Hugging Face key not configured. Using category-based fallback.",
      };
    }

    const hf = new HfInference(config.HUGGINGFACE_API_KEY);
    const availableProducts = await Product.find({ stock: { $gt: 0 } }).limit(20).lean();

    const prompt = `Based on user history, recommend 4 products from the following list. Return ONLY strict JSON in the format: {"recommendations": [{"productId": "string"}]}. Available products: ${JSON.stringify(
      availableProducts.map(p => ({ id: p._id, name: p.name, category: p.category }))
    )}`;

    const response = await hf.textGeneration({
      model: config.HUGGINGFACE_MODEL,
      inputs: prompt,
      parameters: { max_new_tokens: 200, temperature: 0.3, return_full_text: false },
    });

    const text = response.generated_text || "";
    const jsonMatch = text.match(/\{[\s\S]*\}/);

    if (jsonMatch) {
      const parsed = JSON.parse(jsonMatch[0]);
      const ids = parsed.recommendations.map(r => r.productId);
      const recommendedProducts = await Product.find({ _id: { $in: ids } }).lean();

      if (recommendedProducts.length > 0) {
        return {
          recommendedProducts,
          source: "huggingface",
          reason: "Recommendations generated by Hugging Face.",
        };
      }
    }

    return {
      recommendedProducts: fallback,
      source: "fallback",
      reason: "Could not parse Hugging Face response. Using fallback.",
    };
  } catch (error) {
    const fallback = await getFallbackRecommendations(userId);
    return {
      recommendedProducts: fallback,
      source: "fallback",
      reason: "Hugging Face API call failed. Using category-based fallback.",
    };
  }
};

module.exports = {
  getRecommendations,
};
